In [24]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import f1_score,classification_report
from sklearn.ensemble import ExtraTreesClassifier
import os
from IPython.core.display import HTML, display

from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_blobs
import matplotlib.pyplot as plt

C:\Users\fatim\AppData\Local\Temp\ipykernel_12588\1444124414.py:16: DeprecationWarning: Importing display from IPython.core.display is deprecated since IPython 7.14, please import from IPython display
  from IPython.core.display import HTML, display


In [25]:
import pandas as pd
import numpy as np
df = pd.read_csv(r"C:\Users\fatim\OneDrive\Desktop\labels.csv")
df = df.drop("text_ocr", axis = 1)
df = df.drop('Unnamed: 0',axis = 1)
df

image_name                                     text_corrected  \
0        image_1.jpg  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   
1       image_2.jpeg  The best of #10 YearChallenge! Completed in le...   
2        image_3.JPG  Sam Thorne @Strippin ( Follow Follow Saw every...   
3        image_4.png              10 Year Challenge - Sweet Dee Edition   
4        image_5.png  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   
...              ...                                                ...   
6987  image_6988.jpg  Tuesday is Mardi Gras Wednesday is Valentine's...   
6988  image_6989.jpg  MUST WATCH MOVIES OF 2017 ITI Chennai memes MA...   
6989  image_6990.png  LESS MORE TALKING PLANNING SODA JUNK FOOD COMP...   
6990  image_6991.jpg  When I have time is a fantasy. no one has time...   
6991  image_6992.jpg  The starting point for every good idea is "Wha...   

     overall_sentiment  
0        very_positive  
1        very_positive  
2             positive  
3             positive  
4              neutral  
...                ...  
6987           neutral  
6988           neutral  
6989          positive  
6990     very_positive  
6991          positive  

[6992 rows x 3 columns]

In [26]:
df2 = df.fillna(value = 'nothing')
df2['text_corrected'] = df2['text_corrected'].astype(str)
df1 = df2['text_corrected'].tolist()
df1

['LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIKUT TREND PLAY THE 10 YEARS CHALLENGE AT FACEBOOK imgflip.com',
 'The best of #10 YearChallenge! Completed in less the 4 years. Kudus to @narendramodi ji 8:05 PM - 16 Jan 2019 from Mumbai  India',
 "Sam Thorne @Strippin ( Follow Follow Saw everyone posting these 2009 vs 2019 pics so here's mine 6:23 PM - 12 Jan 2019 O 636 Retweets 3 224 LIKES 65 636 3.2K",
 '10 Year Challenge - Sweet Dee Edition',
 '10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious 10 Year Challenge Memes | What is #10 Year Challenge?',
 '1998: "Don\'t get in car with strangers" 2008: "Don\'t meet people from the internet alone." MemeCenter.com 2019: UBER.. Order yourself a stranger from the internet to get into a car with alone.',
 '10 years challenge is lit af Üs & B erg 1945 1955 Wow such transformation!',
 '10 Year Challenge emotional edition boredpanda.com',
 'Fornite died in 10 months but Minecraft never died in 10 years I am so proud of this community',
 "FACEBOOK '10 Y

In [27]:
import re
import string
from nltk import WordNetLemmatizer
from nltk.stem.snowball import SnowballStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
import nltk
from nltk.corpus import stopwords
def remove(string):
    return string.replace("  ", '').replace("   ", '').replace("aaaaa" , "a").replace("aaaaaaaa" , "a").replace("eeeeeeeeeeeeeee", "ee").replace("aaaa", "a")

#!"#$%&'()*+, -./:;<=>?@[\]^_`{|}~

li = []
pattern = r'[0-9]'
for i in df1:
    x = i.lower()
    s = x.replace("'t" , " not").replace("'re" , " are").replace("cap'n" , "captain").replace("'ll" , " will").replace("'s" , " is").replace("'m" , " am").replace("'ve", " have").replace("'d" , " had").replace("let's" , "let us")
    x = re.sub(r'[^a-zA-Z0-9\s]+', " " , s)#removes special char
    y = re.sub('http://\S+|https://\S+', '', x)
    y = re.sub(pattern, '', x)
    h = remove(y)
    li.append(h)
    
li

vectorizer = TfidfVectorizer()
x = vectorizer.fit_transform(li)
print(x.shape)
li


(6992, 16839)


['look there my friend lightyear now all sohalikut trend play theyears challenge at facebook imgflip com',
 'the best of yearchallengecompleted in less theyearskudus tonarendramodi ji pmjanfrom mumbaiindia',
 'sam thornestrippin follow follow saw everyone posting thesevspics so here is mine pmjanoretweets likesk',
 ' year challenge sweet dee edition',
 ' year challenge with no filterhilariousyear challenge memes what is year challenge ',
 ' don not get in car with strangers don not meet people from the internet alonememecenter com uberorder yourself a stranger from the internet to get into a car with alone ',
 ' years challenge is lit afs b erg wow such transformation ',
 ' year challenge emotional edition boredpanda com',
 'fornite died inmonths but minecraft never died inyears i am so proud of this community',
 'facebook year challengea ploy or a simple mememo by exo hminh lejan ',
 'probably the first man to doyear challenge chennai pasanga da',
 'state dining room in the white hous

In [28]:
y = df2["overall_sentiment"]
y

0       very_positive
1       very_positive
2            positive
3            positive
4             neutral
            ...      
6987          neutral
6988          neutral
6989         positive
6990    very_positive
6991         positive
Name: overall_sentiment, Length: 6992, dtype: object

In [29]:
d={'very_negative':-1,'negative':-1,'neutral':0, 'very_positive':1 ,'positive' :1}
df2["overall_sentiment"]=df2["overall_sentiment"].map(d)
y = df2["overall_sentiment"]
print (y)

0       1
1       1
2       1
3       1
4       0
       ..
6987    0
6988    0
6989    1
6990    1
6991    1
Name: overall_sentiment, Length: 6992, dtype: int64


Train test

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
X_train, X_test, y_train, y_test =train_test_split(x, y, test_size=0.2 , random_state=210 ,shuffle = True)
print('Shape of X_train = ', X_train.shape)
print('Shape of y_train = ', y_train.shape)
print('Shape of X_test = ', X_test.shape)
print('Shape of y_test = ', y_test.shape)

Shape of X_train =  (5593, 16839)
Shape of y_train =  (5593,)
Shape of X_test =  (1399, 16839)
Shape of y_test =  (1399,)


In [32]:
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import RobustScaler 

In [33]:
sc = RobustScaler(with_centering=False)
sc.fit(X_train)
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

In [34]:
sc = StandardScaler(with_mean=False)
sc.fit(X_train)
X_train_sc = sc.transform(X_train)
X_test_sc = sc.transform(X_test)

In [1331]:
#print(X_test_sc[0:5])

In [1332]:
#X_train_sc =  pd.DataFrame(X_train_sc, columns = ['text_corrected'])
#X_test_sc =  pd.DataFrame(X_test_sc, columns = ['text_corrected'])

Decision tree

In [35]:
#test_size=0.3 , random_state= 90
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report 
from sklearn.metrics import confusion_matrix
clf = tree.DecisionTreeClassifier(criterion='entropy' , min_samples_split = 5) 


In [42]:
listt = []
clf = clf.fit(X_train, y_train)
pred=clf.predict(X_test)
listt.append(pred)
print (pred)
clf.score(X_test,y_test)

[1 1 0 ... 1 1 1]


0.45675482487491065

In [43]:
listt

[array([1, 1, 0, ..., 1, 1, 1], dtype=int64)]

In [142]:
from sklearn.metrics import f1_score,classification_report
f1 = f1_score(y_test, pred,average='macro')*100
print("F1 Score" , f1)
print("Report : \n", classification_report(y_test, pred))
confusion_matrix(pred,y_test)

F1 Score 35.930193508420146
Report : 
               precision    recall  f1-score   support

          -1       0.13      0.11      0.12       188
           0       0.35      0.30      0.32       686
           1       0.61      0.67      0.64      1224

    accuracy                           0.50      2098
   macro avg       0.36      0.36      0.36      2098
weighted avg       0.48      0.50      0.49      2098



array([[ 21,  58,  83],
       [ 59, 204, 321],
       [108, 424, 820]], dtype=int64)

In [13]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_knn_Model.pkl"" 

with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(clf, file)


In [36]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_Decision tree_Model.pkl" 
with open(Pkl_Filename, 'rb') as file:  
    dt = pickle.load(file)

dt

DecisionTreeClassifier(criterion='entropy', min_samples_split=5)

KNN

In [37]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report 
from sklearn.metrics import confusion_matrix
knn=KNeighborsClassifier(n_neighbors = 3 ,weights = 'distance' , algorithm = 'brute' )

In [48]:
#test_size=0.2 , random_state=120
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report 
from sklearn.metrics import confusion_matrix
knn=KNeighborsClassifier(n_neighbors = 3 ,weights = 'distance' , algorithm = 'brute' )
knn.fit(X_train, y_train)
pred=knn.predict(X_test)
listt.append(pred)
knn.score(X_test,y_test)
f1 = f1_score(y_test, pred, average='macro')*100
print("F1 Score" , f1)

print("Report : \n", classification_report(y_test, pred))
confusion_matrix(pred,y_test)

F1 Score 33.5526170038895
Report : 
               precision    recall  f1-score   support

          -1       0.09      0.06      0.07       120
           0       0.33      0.28      0.30       437
           1       0.60      0.67      0.63       842

    accuracy                           0.50      1399
   macro avg       0.34      0.34      0.34      1399
weighted avg       0.47      0.50      0.48      1399



array([[  7,  22,  49],
       [ 26, 122, 225],
       [ 87, 293, 568]], dtype=int64)

In [49]:
listt

[array([1, 1, 0, ..., 1, 1, 1], dtype=int64),
 array([1, 0, 1, ..., 1, 0, 1], dtype=int64),
 array([ 1,  0,  0, ...,  1,  1, -1], dtype=int64),
 array([1, 0, 1, ..., 1, 0, 1], dtype=int64),
 array([1, 0, 1, ..., 1, 0, 1], dtype=int64)]

In [12]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_knn_Model.pkl"  
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(knn, file)

In [38]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_knn_Model.pkl""  
with open(Pkl_Filename, 'rb') as file:  
    Pickled_knn_Model = pickle.load(file)

Pickled_knn_Model

KNeighborsClassifier(algorithm='brute', n_neighbors=3, weights='distance')

Logistic Regression

In [39]:
#test_size=0.2 , random_state= 210
from sklearn.linear_model import LogisticRegression
clf1 = LogisticRegression(penalty = 'none')



In [52]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import classification_report 
clf.fit(X_train, y_train)
p=clf.predict(X_test)
listt.append(p)
print ("Accuracy : " , clf.score(X_test,y_test)*100) 
f1 = f1_score(y_test, p, average='macro')*100
print("F1 score" , f1)
print("Report : \n", classification_report(y_test, p))
confusion_matrix(p,y_test)

Accuracy :  47.96283059328091
F1 score 35.81788552985528
Report : 
               precision    recall  f1-score   support

          -1       0.14      0.13      0.14       120
           0       0.33      0.34      0.33       437
           1       0.61      0.60      0.60       842

    accuracy                           0.48      1399
   macro avg       0.36      0.36      0.36      1399
weighted avg       0.48      0.48      0.48      1399



array([[ 16,  28,  68],
       [ 35, 147, 266],
       [ 69, 262, 508]], dtype=int64)

In [53]:
listt

[array([1, 1, 0, ..., 1, 1, 1], dtype=int64),
 array([1, 0, 1, ..., 1, 0, 1], dtype=int64),
 array([ 1,  0,  0, ...,  1,  1, -1], dtype=int64),
 array([1, 0, 1, ..., 1, 0, 1], dtype=int64),
 array([1, 0, 1, ..., 1, 0, 1], dtype=int64),
 array([1, 1, 0, ..., 1, 1, 1], dtype=int64),
 array([1, 1, 0, ..., 1, 1, 1], dtype=int64),
 array([1, 0, 0, ..., 1, 1, 1], dtype=int64)]

In [164]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_regression_Model.pkl" 
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(clf1, file)

In [40]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_regression_Model.pkl" 
with open(Pkl_Filename, 'rb') as file:  
    lr = pickle.load(file)

lr

LogisticRegression(penalty='none')

In [19]:
from sklearn.ensemble import VotingClassifier
logReg= LogisticRegression()
dTree= DecisionTreeClassifier()
svm= KNeighborsClassifier()
#rm = RandomForestClassifier()
voting_clf = VotingClassifier(estimators=[('knn', svm), ('LogReg', logReg) , ('Dtree' , dTree)], voting='soft')

In [187]:
voting_clf.fit(X_train, y_train)
predictions = voting_clf.predict(X_test)
f1 = f1_score(y_test, predictions, average='macro')*100
print("F1 Score" , f1)
#Evaluation matrics
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

F1 Score 35.96325013129889
[[  6  27  87]
 [  9 127 301]
 [ 25 187 630]]
              precision    recall  f1-score   support

          -1       0.15      0.05      0.07       120
           0       0.37      0.29      0.33       437
           1       0.62      0.75      0.68       842

    accuracy                           0.55      1399
   macro avg       0.38      0.36      0.36      1399
weighted avg       0.50      0.55      0.52      1399



In [24]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_overall_f1.pkl"  
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(voting_clf, file)

In [20]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_overall_f1.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    oor = pickle.load(file)

oor

VotingClassifier(estimators=[('knn', KNeighborsClassifier()),
                             ('LogReg', LogisticRegression()),
                             ('Dtree', DecisionTreeClassifier())],
                 voting='soft')

# Images

In [21]:
from tqdm.notebook import tqdm
import matplotlib.pyplot as plt
from PIL import Image
from PIL import ImageFile
import IPython.display as ipd
import skimage
import sklearn
from skimage import filters
from skimage import feature
from skimage.io import imread, imshow
from skimage.feature import hog
import re
import os

In [22]:
ImageFile.LOAD_TRUNCATED_IMAGES=True
path=(r"C:\Users\fatim\OneDrive\Desktop\images\\")
li=os.listdir(path)
images=[]
i=0
for file in li:
    #z=imread(path+file,as_gray=True)
    z=skimage.transform.resize(imread(path+file,as_gray=True),(100,100))
    fd, hog_image = hog(z, orientations=9, pixels_per_cell=(8, 8), cells_per_block=(2, 2), visualize=True)
    images.append(fd)
    i=i+1
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277


C:\Users\fatim\anaconda3\lib\site-packages\PIL\TiffImagePlugin.py:822: UserWarning: Corrupt EXIF data.  Expecting to read 2 bytes but only got 0. 
  warnings.warn(str(msg))


6128
6129
6130
6131
6132
6133
6134
6135
6136
6137
6138
6139
6140
6141
6142
6143
6144
6145
6146
6147
6148
6149
6150
6151
6152
6153
6154
6155
6156
6157
6158
6159
6160
6161
6162
6163
6164
6165
6166
6167
6168
6169
6170
6171
6172
6173
6174
6175
6176
6177
6178
6179
6180
6181
6182
6183
6184
6185
6186
6187
6188
6189
6190
6191
6192
6193
6194
6195
6196
6197
6198
6199
6200
6201
6202
6203
6204
6205
6206
6207
6208
6209
6210
6211
6212
6213
6214
6215
6216
6217
6218
6219
6220
6221
6222
6223
6224
6225
6226
6227
6228
6229
6230
6231
6232
6233
6234
6235
6236
6237
6238
6239
6240
6241
6242
6243
6244
6245
6246
6247
6248
6249
6250
6251
6252
6253
6254
6255
6256
6257
6258
6259
6260
6261
6262
6263
6264
6265
6266
6267
6268
6269
6270
6271
6272
6273
6274
6275
6276
6277
6278
6279
6280
6281
6282
6283
6284
6285
6286
6287
6288
6289
6290
6291
6292
6293
6294
6295
6296
6297
6298
6299
6300
6301
6302
6303
6304
6305
6306
6307
6308
6309
6310
6311
6312
6313
6314
6315
6316
6317
6318
6319
6320
6321
6322
6323
6324
6325
6326
6327


In [23]:
Dataframe={'Name':li,'Images':images}
df2=pd.DataFrame(Dataframe)
df2

Name                                             Images
0        image_1.jpg  [0.053448925985925905, 0.0, 0.0, 0.0, 0.010437...
1       image_10.png  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2      image_100.jpg  [0.1488707172512588, 0.006435086319828711, 0.0...
3     image_1000.png  [0.06601667410804951, 0.11417608101012028, 0.2...
4     image_1001.png  [0.02053449594822163, 0.0, 0.0, 0.0, 0.0422566...
...              ...                                                ...
6987  image_995.jpeg  [0.26099513940390795, 0.10958524078352515, 0.0...
6988   image_996.jpg  [0.13722077024497917, 0.24780952266299242, 0.2...
6989   image_997.jpg  [0.3081175798927836, 0.10382214748021326, 0.08...
6990   image_998.jpg  [0.2546846532841212, 0.17399866818313922, 0.25...
6991   image_999.png  [0.0, 0.06521171236379203, 0.0, 0.054961672008...

[6992 rows x 2 columns]

In [24]:
df

image_name                                     text_corrected  \
0        image_1.jpg  LOOK THERE MY FRIEND LIGHTYEAR NOW ALL SOHALIK...   
1       image_2.jpeg  The best of #10 YearChallenge! Completed in le...   
2        image_3.JPG  Sam Thorne @Strippin ( Follow Follow Saw every...   
3        image_4.png              10 Year Challenge - Sweet Dee Edition   
4        image_5.png  10 YEAR CHALLENGE WITH NO FILTER 47 Hilarious ...   
...              ...                                                ...   
6987  image_6988.jpg  Tuesday is Mardi Gras Wednesday is Valentine's...   
6988  image_6989.jpg  MUST WATCH MOVIES OF 2017 ITI Chennai memes MA...   
6989  image_6990.png  LESS MORE TALKING PLANNING SODA JUNK FOOD COMP...   
6990  image_6991.jpg  When I have time is a fantasy. no one has time...   
6991  image_6992.jpg  The starting point for every good idea is "Wha...   

     overall_sentiment  
0        very_positive  
1        very_positive  
2             positive  
3             positive  
4              neutral  
...                ...  
6987           neutral  
6988           neutral  
6989          positive  
6990     very_positive  
6991          positive  

[6992 rows x 3 columns]

In [26]:
df2['Flatten_Images']=0
df2['Flatten_Images'][0]=np.array([1,2], dtype=object)

C:\Users\fatim\AppData\Local\Temp\ipykernel_9956\680673434.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Flatten_Images'][0]=np.array([1,2], dtype=object)


In [27]:
for i in range(0 , len(df2)):
    x=np.array(df2['Images'][i])
    df2['Flatten_Images'][i]=x.flatten()
    i=i+1
    #print(i)

df2

Name                                             Images  \
0        image_1.jpg  [0.053448925985925905, 0.0, 0.0, 0.0, 0.010437...   
1       image_10.png  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2      image_100.jpg  [0.1488707172512588, 0.006435086319828711, 0.0...   
3     image_1000.png  [0.06601667410804951, 0.11417608101012028, 0.2...   
4     image_1001.png  [0.02053449594822163, 0.0, 0.0, 0.0, 0.0422566...   
...              ...                                                ...   
6987  image_995.jpeg  [0.26099513940390795, 0.10958524078352515, 0.0...   
6988   image_996.jpg  [0.13722077024497917, 0.24780952266299242, 0.2...   
6989   image_997.jpg  [0.3081175798927836, 0.10382214748021326, 0.08...   
6990   image_998.jpg  [0.2546846532841212, 0.17399866818313922, 0.25...   
6991   image_999.png  [0.0, 0.06521171236379203, 0.0, 0.054961672008...   

                                         Flatten_Images  
0     [0.053448925985925905, 0.0, 0.0, 0.0, 0.010437...  
1     [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2     [0.1488707172512588, 0.006435086319828711, 0.0...  
3     [0.06601667410804951, 0.11417608101012028, 0.2...  
4     [0.02053449594822163, 0.0, 0.0, 0.0, 0.0422566...  
...                                                 ...  
6987  [0.26099513940390795, 0.10958524078352515, 0.0...  
6988  [0.13722077024497917, 0.24780952266299242, 0.2...  
6989  [0.3081175798927836, 0.10382214748021326, 0.08...  
6990  [0.2546846532841212, 0.17399866818313922, 0.25...  
6991  [0.0, 0.06521171236379203, 0.0, 0.054961672008...  

[6992 rows x 3 columns]

In [28]:
df2 = df2.drop('Images',axis = 1)
df2

Name                                     Flatten_Images
0        image_1.jpg  [0.053448925985925905, 0.0, 0.0, 0.0, 0.010437...
1       image_10.png  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
2      image_100.jpg  [0.1488707172512588, 0.006435086319828711, 0.0...
3     image_1000.png  [0.06601667410804951, 0.11417608101012028, 0.2...
4     image_1001.png  [0.02053449594822163, 0.0, 0.0, 0.0, 0.0422566...
...              ...                                                ...
6987  image_995.jpeg  [0.26099513940390795, 0.10958524078352515, 0.0...
6988   image_996.jpg  [0.13722077024497917, 0.24780952266299242, 0.2...
6989   image_997.jpg  [0.3081175798927836, 0.10382214748021326, 0.08...
6990   image_998.jpg  [0.2546846532841212, 0.17399866818313922, 0.25...
6991   image_999.png  [0.0, 0.06521171236379203, 0.0, 0.054961672008...

[6992 rows x 2 columns]

In [29]:
lst = df2['Name'].tolist()
print(type(lst))


<class 'list'>


citation: https://stackoverflow.com/questions/37693600/how-to-sort-dataframe-based-on-particular-stringcolumns-using-python-pandas

In [30]:
df2['sort'] = df2['Name'].str.extract('(\d+)', expand=False).astype(int)
df2.sort_values('sort',inplace=True, ascending=True)
df2 = df2.drop('sort', axis=1)
df2

Name                                     Flatten_Images
0        image_1.jpg  [0.053448925985925905, 0.0, 0.0, 0.0, 0.010437...
1111    image_2.jpeg  [0.05906419182650314, 0.0, 0.0, 0.023782648578...
2222     image_3.JPG  [0.10316074073941371, 0.0022145026158177246, 0...
3333     image_4.png  [0.031171597164796516, 0.0164606501420169, 0.0...
4444     image_5.png  [0.08100109336614315, 0.05807039867462751, 0.0...
...              ...                                                ...
6653  image_6988.jpg  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
6654  image_6989.jpg  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
6656  image_6990.png  [0.3099219179975825, 0.0, 0.0, 0.0, 0.30992191...
6657  image_6991.jpg  [0.4037519933771422, 0.4037519933771422, 0.0, ...
6658  image_6992.jpg  [0.0751376587884775, 0.06251825586375806, 0.02...

[6992 rows x 2 columns]

In [31]:
df2 = df2.reset_index(drop=True)
df2

Name                                     Flatten_Images
0        image_1.jpg  [0.053448925985925905, 0.0, 0.0, 0.0, 0.010437...
1       image_2.jpeg  [0.05906419182650314, 0.0, 0.0, 0.023782648578...
2        image_3.JPG  [0.10316074073941371, 0.0022145026158177246, 0...
3        image_4.png  [0.031171597164796516, 0.0164606501420169, 0.0...
4        image_5.png  [0.08100109336614315, 0.05807039867462751, 0.0...
...              ...                                                ...
6987  image_6988.jpg  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
6988  image_6989.jpg  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...
6989  image_6990.png  [0.3099219179975825, 0.0, 0.0, 0.0, 0.30992191...
6990  image_6991.jpg  [0.4037519933771422, 0.4037519933771422, 0.0, ...
6991  image_6992.jpg  [0.0751376587884775, 0.06251825586375806, 0.02...

[6992 rows x 2 columns]

In [32]:
df2['overall_sentiment'] = df['overall_sentiment']
df2

Name                                     Flatten_Images  \
0        image_1.jpg  [0.053448925985925905, 0.0, 0.0, 0.0, 0.010437...   
1       image_2.jpeg  [0.05906419182650314, 0.0, 0.0, 0.023782648578...   
2        image_3.JPG  [0.10316074073941371, 0.0022145026158177246, 0...   
3        image_4.png  [0.031171597164796516, 0.0164606501420169, 0.0...   
4        image_5.png  [0.08100109336614315, 0.05807039867462751, 0.0...   
...              ...                                                ...   
6987  image_6988.jpg  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
6988  image_6989.jpg  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
6989  image_6990.png  [0.3099219179975825, 0.0, 0.0, 0.0, 0.30992191...   
6990  image_6991.jpg  [0.4037519933771422, 0.4037519933771422, 0.0, ...   
6991  image_6992.jpg  [0.0751376587884775, 0.06251825586375806, 0.02...   

     overall_sentiment  
0        very_positive  
1        very_positive  
2             positive  
3             positive  
4              neutral  
...                ...  
6987           neutral  
6988           neutral  
6989          positive  
6990     very_positive  
6991          positive  

[6992 rows x 3 columns]

In [33]:
y = df2['overall_sentiment']
y

0       very_positive
1       very_positive
2            positive
3            positive
4             neutral
            ...      
6987          neutral
6988          neutral
6989         positive
6990    very_positive
6991         positive
Name: overall_sentiment, Length: 6992, dtype: object

In [34]:
d={'very_negative':-1,'negative':-1,'neutral':0, 'very_positive':1 ,'positive' :1}
df2["overall_sentiment"]=df2["overall_sentiment"].map(d)
y = df2["overall_sentiment"]
print (y)

0       1
1       1
2       1
3       1
4       0
       ..
6987    0
6988    0
6989    1
6990    1
6991    1
Name: overall_sentiment, Length: 6992, dtype: int64


In [35]:
x = df2['Flatten_Images']



In [36]:
X_train, X_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=30 ,shuffle=True)

In [ ]:
135

Support Vector Machine (SVM)

In [37]:
#test_size=0.15, random_state=120
from sklearn.svm import SVC
svc = SVC(kernel = 'linear' , C = 2.0 , probability=True)

In [68]:
svc.fit(list(X_train), list(y_train))
pred = svc.predict(list(X_test))
listt.append(pred)
f1 = f1_score(y_test, pred, average='macro')*100
print("F1 Score" , f1)

F1 Score 35.43632281719343


In [69]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_SVC_f1.pkl"  
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(svc, file)

In [38]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_SVC_f1.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    sv = pickle.load(file)

sv

SVC(C=2.0, kernel='linear', probability=True)

Naive Bayes


In [39]:
#0.2, 10
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB(var_smoothing = 3.9)


In [42]:
gnb.fit(list(X_train), y_train)
pr = gnb.predict(list(X_test))
listt.append(pr)
f1 = f1_score(y_test, pr, average='macro')*100
print("F1 Score" , f1)

F1 Score 34.47591722293575


In [43]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_Gaussian_f1.pkl"  
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(gnb, file)

In [40]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_Gaussian_f1.pkl"  
with open(Pkl_Filename, 'rb') as file:  
    g = pickle.load(file)

g

GaussianNB(var_smoothing=3.9)

AdaBoostClassifier

In [23]:
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100, random_state=0)

In [22]:
clf.fit(list(X_train), y_train)
p = clf.predict(list(X_test))
listt.append(p)
f1 = f1_score(y_test, p, average='macro')*100
print("F1 Score" , f1)

F1 score 32.52617628837562


In [61]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_AdaBoostClassifier_f1.pkl"  
with open(Pkl_Filename, 'wb') as file:  
    pickle.dump(clf, file)

In [42]:
import pickle
Pkl_Filename = r"C:\Users\Duaa\Pickle_AdaBoostClassifier_f1.pkl" 
with open(Pkl_Filename, 'rb') as file:  
    ada = pickle.load(file)

ada

AdaBoostClassifier(n_estimators=100, random_state=0)

In [45]:
o.fit(list(X_train), y_train)
predictions = o.predict(list(X_test))
f1 = f1_score(y_test, predictions, average='macro')*100
print("F1 Score" , f1)

C:\Users\fatim\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


F1 Score 32.1050507748071


In [56]:
df = pd.DataFrame(listt)
df

0     1     2     3     4     5     6     7     8     9     ...  1389  \
0     1     1     0     1     1     0     0     0     0     1  ...    -1   
1     1     0     1     1     0     1     1     1     1     1  ...     0   
2     1     0     0     1     1     0     1     0     0     1  ...    -1   
3     1     0     1     1     0     1     1     1     1     1  ...     0   
4     1     0     1     1     0     1     1     1     1     1  ...     0   
5     1     1     0     0     1     0     1     0     0     1  ...    -1   
6     1     1     0     0     1     0     1     0     0     1  ...    -1   
7     1     0     0     1     1     0     1    -1     0     1  ...    -1   

   1390  1391  1392  1393  1394  1395  1396  1397  1398  
0     1     1     1    -1     0     0     1     1     1  
1     0     1     1     1     0     0     1     0     1  
2     0     1     1    -1     1     0     1     1    -1  
3     0     1     1     1     0     0     1     0     1  
4     0     1     1     1     0     0     1     0     1  
5     1     1     1    -1     0     0     1     1     1  
6     1     1     1    -1     0     0     1     1     1  
7     0     1     1    -1     0     0     1     1     1  

[8 rows x 1399 columns]

In [71]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
m = df.mode(axis = 0)

In [75]:
a = m.iloc[[0]]

In [77]:
a = np.array(a).T
a

array([[1.],
       [0.],
       [0.],
       ...,
       [1.],
       [1.],
       [1.]])

In [78]:
f1 = f1_score(y_test, a, average='macro')*100
print("F1 Score" , f1)

F1 Score 35.67898115588532
